stages:
  - tests
  - release
  - publish

tests:
  stage: tests
  image: docker.gamechanger.io/docker-compose-cleanup:latest
  script:
    - docker-compose build --pull tests
    - docker-compose run --rm tests
  only:
    refs:
      - branches

create tag:
  stage: release
  image: docker.gamechanger.io/bumpversion-git-tag
  script:
    - bumpversion --version=major
  only:
    refs:
      - master

build docker image:
  stage: publish
  image: docker.gamechanger.io/docker-build-image
  script:
    - docker-build --image-name=lox
  only:
    refs:
      - master