stages:
  - tests

tests:
  stage: tests
  image: docker.gamechanger.io/docker-compose-cleanup:latest
  script:
    - docker-compose build --pull tests
    - docker-compose run --rm tests
  only:
    refs:
      - branches
