#%RAML 0.8
---
title: Lox
baseUri: "http://lox.yourdomain.com"
documentation:
  - title: "Lox: A simple distributed lock manager"
    content: |
      Lox exposes an HTTP API to help you manage distributed locks. That API is documented here.

      You may also be interested in [the product page](http://gamechanger.github.io/lox) or [the GitHub repository](http://github.com/gamechanger/lox)
/lock:
  description: Endpoints to acquire and release distributed locks
  post:
    description: Attempt to acquire a shared lock.
    queryParameters:
      key:
        displayName: key
        type: string
        description: An identifier for the shared lock you want to acquire
        example: lox.shared.lock.123
        required: true
      maximumLocks:
        displayName: maximumLocks
        type: integer
        description: The maximum allowable number of held locks after a successful lock acquisition. If this many locks or more are already held, acquisition will fail.
        example: 5
        required: true
      ttlSeconds:
        displayName: ttlSeconds
        type: number
        description: The number of seconds for which to hold the lock
        example: 60
        required: true
    responses:
      201:
        description: Successfully acquired a shared lock
        body:
          application/json:
            example: |
              {"lockId": "3885b1e0-022c-11e4-b7c7-6b932dd1bfa1"}
      204:
        description: Could not acquire a shared lock subject to `maximumLocks`
  /{lockId}:
    delete:
      description: Release a held lock.
      queryParameters:
        lockId:
          displayName: lockId
          type: string
          description: The lock ID provided by a previously successful lock acquisition
          example: 3885b1e0-022c-11e4-b7c7-6b932dd1bfa1
          required: true
      responses:
        204:
          description: If a lock was held, it has been released
